esphome:
  name: "athom-rgbct-light"
  friendly_name: "Athom RGBCT Light"
  name_add_mac_suffix: true

esp8266:
  board: esp8285
  restore_from_flash: true

globals:
  - id: fast_reboot
    type: int
    restore_value: yes
    initial_value: '0'

  - id: factory_reset_reboot_counter
    type: int
    initial_value: '2'

logger:
  baud_rate: 0
  level: info

script:
  - id: fast_reboot_factory_reset
    then:
      - if:
          condition:
            lambda: return ( id(fast_reboot) >= id(factory_reset_reboot_counter) );
          then:
            - lambda: |-
                ESP_LOGI("Fast Boot Factory Reset", "Performing factotry reset");
                id(fast_reboot) = 0;
                fast_reboot->loop();
                global_preferences->sync();
            - button.press: factory_reset_button
      - lambda: |-
          if(id(fast_reboot) > 0)
            ESP_LOGI("Fast Boot Factory Reset", "Quick reboot %d/%d, do it %d more times to factory reset", id(fast_reboot), id(factory_reset_reboot_counter), id(factory_reset_reboot_counter) - id(fast_reboot));
          id(fast_reboot) += 1;
          fast_reboot->loop();
          global_preferences->sync();
      - delay: 10s
      - lambda: |-
          id(fast_reboot) = 0;
          fast_reboot->loop();
          global_preferences->sync();

wifi:
  id: wifi_component
  ap:
    ap_timeout: 0s
  reboot_timeout: 0s

captive_portal:
    
web_server:

api:
  reboot_timeout: 0s

ota:
  safe_mode: false

prometheus:

debug:
  update_interval: 5s

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 15s

  - platform: wifi_signal
    name: "WiFi Signal"
    unit_of_measurement: "dB"
    icon: 'mdi:signal'
    update_interval: 15s

  - platform: debug
    free:
      name: "Debug: Heap Free"
    fragmentation:
      name: "Debug: Heap Fragmentation"
    block:
      name: "Debug: Heap Largest Contiguous Free Block"
    loop_time:
      name: "Debug: Loop Time"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Wifi Info: IP Address"
    ssid:
      name: "Wifi Info: SSID"
    bssid:
      name: "Wifi Info: BSSID"
    mac_address:
      name: "Wifi Info: MAC Address"
    dns_address:
      name: "Wifi Info: DNS Address"

  - platform: debug
    device:
      name: "Debug: Device Info"
    reset_reason:
      name: "Debug: Reset Reason"

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    min_power: 0
    max_power: 0.53

  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    min_power: 0
    max_power: 0.24

  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    id: color_temperature
    inverted: true
    pin: GPIO13

light:
  - platform: rgbct
    id: rgbct_light
    default_transition_length: 0ms
    restore_mode: RESTORE_DEFAULT_ON
    red: red_output
    green: green_output
    blue: blue_output
    color_temperature: color_temperature
    white_brightness: white_output
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    color_interlock: true

switch:
  - platform: template
    name: "Power"
    id: rgbct_light_power_switch
    icon: mdi:light-switch
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: ""
    device_class: switch
    lambda: |-
      bool is_on;
      id(rgbct_light).current_values_as_binary(&is_on);
      if (is_on) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
     - light.turn_on: rgbct_light
    turn_off_action:
      - light.turn_off: rgbct_light

  - platform: template
    name: "RGB"
    id: rgbct_light_rgb_switch
    icon: mdi:palette
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    device_class: switch
    lambda: |-
      ColorMode color_mode = id(rgbct_light).current_values.get_color_mode();
      if (color_mode == ColorMode::RGB)
        return true;
      return false;
    turn_on_action:
      then:
        - light.control:
            id: rgbct_light
            color_mode: RGB
    turn_off_action:
      then:
        - light.control:
            id: rgbct_light
            color_mode: COLOR_TEMPERATURE

number:
  - platform: template
    name: "Red"
    icon: mdi:palette
    entity_category: config
    unit_of_measurement: "%"
    mode: slider
    min_value: 0
    max_value: 100
    step: 0.1
    lambda: |-
      return id(rgbct_light).current_values.get_red() * 100.0;
    update_interval: 200ms
    set_action:
      - light.control:
          id: rgbct_light
          color_mode: RGB
          red: !lambda "return float(x) / 100.0;"

  - platform: template
    name: "Green"
    icon: mdi:palette
    entity_category: config
    unit_of_measurement: "%"
    mode: slider
    min_value: 0
    max_value: 100
    step: 0.1
    lambda: |-
      return id(rgbct_light).current_values.get_green() * 100.0;
    update_interval: 200ms
    set_action:
      - light.control:
          id: rgbct_light
          color_mode: RGB
          green: !lambda "return float(x) / 100.0;"

  - platform: template
    name: "Blue"
    icon: mdi:palette
    entity_category: config
    unit_of_measurement: "%"
    mode: slider
    min_value: 0
    max_value: 100
    step: 0.1
    lambda: |-
      return id(rgbct_light).current_values.get_blue() * 100.0;
    update_interval: 200ms
    set_action:
      - light.control:
          id: rgbct_light
          color_mode: RGB
          blue: !lambda "return float(x) / 100.0;"

  - platform: template
    name: "Color Temperature"
    icon: mdi:temperature-celsius
    entity_category: config
    unit_of_measurement: "K"
    mode: slider
    min_value: 2000
    max_value: 6500
    step: 1
    lambda: |-
      return 1000000.0 / id(rgbct_light).current_values.get_color_temperature();
    update_interval: 200ms
    set_action:
      - light.turn_on:
          id: rgbct_light
          color_mode: COLOR_TEMPERATURE
          color_temperature: !lambda |-
            return 1000000.0 / float(x);

  - platform: template
    name: "Brightness"
    icon: mdi:brightness-percent
    unit_of_measurement: "%"
    mode: slider
    min_value: 0
    max_value: 100
    step: 0.1
    lambda: |-
      return id(rgbct_light).current_values.get_brightness() * 100.0;
    update_interval: 200ms
    set_action:
      - light.turn_on:
          id: rgbct_light
          brightness: !lambda "return float(x) / 100.0;"

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset"

  - platform: restart
    name: "Restart"

  - platform: safe_mode
    name: "Safe Mode"