esphome:
  name: "athom-rgbct-light"
  friendly_name: "Athom RGBCT Light"
  name_add_mac_suffix: true
  on_boot:
    - priority: 600.0
      then:
        # - lambda: |-
        #     id(wifi_led_pwm).set_level(0.5);
        #     id(wifi_led_pwm).set_period(1000);
        #     id(wifi_led_pwm).turn_on();
        - script.execute: fast_reboot_factory_reset
  # on_loop:
  #   then:
  #     - lambda: |-
  #         if(id(wifi_component).has_ap() && !id(wifi_component).has_sta()) {
  #           // Captive portal
  #           id(wifi_led_pwm).set_level(0.5);
  #           id(wifi_led_pwm).set_period(200);
  #         } else {
  #           id(wifi_led_pwm).set_period(1000);
  #           if(id(wifi_component).is_connected())
  #             id(wifi_led_pwm).set_level(1);
  #           else
  #             id(wifi_led_pwm).set_level(0.5);
  #         }

esp8266:
  board: esp8285
  restore_from_flash: true

globals:
  - id: fast_reboot
    type: int
    restore_value: yes
    initial_value: '0'

  - id: factory_reset_reboot_counter
    type: int
    initial_value: '2'

logger:

script:
  - id: fast_reboot_factory_reset
    then:
      - if:
          condition:
            lambda: return ( id(fast_reboot) >= id(factory_reset_reboot_counter) );
          then:
            - lambda: |-
                ESP_LOGD("Fast Boot Factory Reset", "Performing factotry reset");
                id(fast_reboot) = 0;
                fast_reboot->loop();
                global_preferences->sync();
            - button.press: factory_reset_button
      - lambda: |-
          if(id(fast_reboot) > 0)
            ESP_LOGD("Fast Boot Factory Reset", "Quick reboot %d/%d, do it %d more times to factory reset", id(fast_reboot), id(factory_reset_reboot_counter), id(factory_reset_reboot_counter) - id(fast_reboot));
          id(fast_reboot) += 1;
          fast_reboot->loop();
          global_preferences->sync();
      - delay: 10s
      - lambda: |-
          id(fast_reboot) = 0;
          fast_reboot->loop();
          global_preferences->sync();

wifi:
  id: wifi_component
  ap:
    ap_timeout: 0s
  reboot_timeout: 0s

captive_portal:
    
web_server:

api:
  reboot_timeout: 0s

ota:
  safe_mode: false

prometheus:

binary_sensor:
  # - platform: status
  #   name: "ESPHome: Status"

sensor:
  # - platform: uptime
  #   name: 'ESPHome: Uptime'
  #   icon: 'mdi:timer-outline'
  #   update_interval: 1s

  # - platform: wifi_signal
  #   name: "ESPHome: WiFi Signal"
  #   unit_of_measurement: "dB"
  #   id: wifi_signal_db
  #   update_interval: 15s
  #   entity_category: "diagnostic"
  #   icon: 'mdi:signal'

text_sensor:
  # - platform: wifi_info
  #   ip_address:
  #     name: "ESPHome: Wifi IP Address"
  #   ssid:
  #     name: "ESPHome: Wifi Connected SSID"
  #   bssid:
  #     name: "ESPHome: Wifi Connected BSSID"
  #   mac_address:
  #     name: "ESPHome: Wifi Mac Wifi Address"
  #   dns_address:
  #     name: "ESPHome: Wifi DNS Address"

# Color correction
# Red 100%
# Green 70%
# Blue 57%

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    # min_power: 0.000499
    min_power: 0
    max_power: 1
    # zero_means_zero: true

  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    # min_power: 0.000499
    min_power: 0
    max_power: 1
    # zero_means_zero: true

  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    # min_power: 0.000499
    min_power: 0
    max_power: 1
    # zero_means_zero: true

  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5
    # min_power: 0.01
    min_power: 0
    max_power: 1
    # zero_means_zero: true

  - platform: esp8266_pwm
    id: color_temperature
    inverted: true
    pin: GPIO13

light:
  - platform: rgbct
    id: rgbct_light
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON
    # on_state:
    #   then:
    #     - lambda: |-
    #         float red, green, blue, color_temperature, white_brightness;
    #         id(rgbct_light).current_values_as_rgbct (
    #           &red, &green, &blue,
    #           &color_temperature, &white_brightness
    #         );

    #         float new_red = float(red) * 100.0;
    #         if (new_red != id(rgbct_number_red).state) {
    #           id(rgbct_number_red).state = new_red;
    #         }

    #         float new_green = float(green) * 100.0;
    #         if (new_green != id(rgbct_number_green).state) {
    #           id(rgbct_number_green).state = new_green;
    #         }

    #         float new_blue = float(blue) * 100.0;
    #         if (new_blue != id(rgbct_number_blue).state) {
    #           id(rgbct_number_blue).state = new_blue;
    #         }

    #         float new_color_temperature = float(color_temperature);
    #         if (new_color_temperature != id(rgbct_number_color_temperature).state) {
    #           id(rgbct_number_color_temperature).state = new_color_temperature;
    #         }

    #         float new_white_brightness = float(white_brightness) * 100.0;
    #         if (new_white_brightness != id(rgbct_number_white_brightness).state) {
    #           id(rgbct_number_white_brightness).state = new_white_brightness;
    #         }
    red: red_output
    green: green_output
    blue: blue_output
    color_temperature: color_temperature
    white_brightness: white_output
    # cold_white_color_temperature: 6000 K
    cold_white_color_temperature: 153 mireds
    # warm_white_color_temperature: 3000 K
    warm_white_color_temperature: 500 mireds
    color_interlock: true

number:
  # - platform: template
  #   name: "RGBCT Light: RGB: Red"
  #   id: rgbct_number_red
  #   unit_of_measurement: "%"
  #   min_value: 0
  #   max_value: 100
  #   step: 1
  #   set_action:
  #     - light.turn_on:
  #         id: rgbct_light
  #         color_mode: RGB
  #         brightness: !lambda |-
  #           float red, green, blue, color_temperature, white_brightness;
  #           id(rgbct_light).current_values_as_rgbct (
  #             &red, &green, &blue,
  #             &color_temperature, &white_brightness
  #           );
  #           if (red > 0 || green > 0 || blue > 0)
  #             return 1;
  #           return 0;
  #         red: !lambda |-
  #           if (x == 0)
  #             return 0;
  #           return float(x)/100.0;
  #   optimistic: true
  #   restore_value: true
  #   initial_value: 1

  # - platform: template
  #   name: "RGBCT Light: RGB: Green"
  #   id: rgbct_number_green
  #   unit_of_measurement: "%"
  #   min_value: 0
  #   max_value: 100
  #   step: 1
  #   set_action:
  #     - light.turn_on:
  #         id: rgbct_light
  #         color_mode: RGB
  #         brightness: !lambda |-
  #           float red, green, blue, color_temperature, white_brightness;
  #           id(rgbct_light).current_values_as_rgbct (
  #             &red, &green, &blue,
  #             &color_temperature, &white_brightness
  #           );
  #           if (red > 0 || green > 0 || blue > 0)
  #             return 1;
  #           return 0;
  #         green: !lambda |-
  #           if (x == 0)
  #             return 0;
  #           return float(x)/100.0;
  #   optimistic: true
  #   restore_value: true
  #   initial_value: 1

  # - platform: template
  #   name: "RGBCT Light: RGB: Blue"
  #   id: rgbct_number_blue
  #   unit_of_measurement: "%"
  #   min_value: 0
  #   max_value: 100
  #   step: 1
  #   set_action:
  #     - light.turn_on:
  #         id: rgbct_light
  #         color_mode: RGB
  #         brightness: !lambda |-
  #           float red, green, blue, color_temperature, white_brightness;
  #           id(rgbct_light).current_values_as_rgbct (
  #             &red, &green, &blue,
  #             &color_temperature, &white_brightness
  #           );
  #           if (red > 0 || green > 0 || blue > 0)
  #             return 1;
  #           return 0;
  #         blue: !lambda |-
  #           if (x == 0)
  #             return 0;
  #           return float(x)/100.0;
  #   optimistic: true
  #   restore_value: true
  #   initial_value: 1

  # - platform: template
  #   name: "RGBCT Light: Color Temperature"
  #   id: rgbct_number_color_temperature
  #   unit_of_measurement: "K"
  #   min_value: 153
  #   max_value: 500
  #   step: 1
  #   set_action:
  #     - light.turn_on:
  #         id: rgbct_light
  #         color_mode: COLOR_TEMPERATURE
  #         color_temperature: !lambda "return x;"
  #   optimistic: true
  #   restore_value: true
  #   initial_value: 153

  # - platform: template
  #   name: "RGBCT Light: Brightness"
  #   id: rgbct_number_white_brightness
  #   unit_of_measurement: "%"
  #   min_value: 0
  #   max_value: 100
  #   step: 1
  #   set_action:
  #     - light.turn_on:
  #         id: rgbct_light
  #         color_mode: COLOR_TEMPERATURE
  #         brightness: !lambda |-
  #           if (x == 0)
  #             return 0;
  #           return float(x)/100.0;
  #   optimistic: true
  #   restore_value: true
  #   initial_value: 1

switch:
  - platform: template
    name: "RGBCT Light: Power"
    id: rgbct_light_power_switch
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      bool is_on;
      id(rgbct_light).current_values_as_binary(&is_on);
      if (is_on) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            switch.is_off: rgbct_light_rgb_switch
          then:
          - light.turn_on:
              id: rgbct_light
              color_mode: COLOR_TEMPERATURE
      - if:
          condition:
            switch.is_on: rgbct_light_rgb_switch
          then:
          - light.turn_on:
              id: rgbct_light
              color_mode: RGB
    turn_off_action:
      - light.turn_off: rgbct_light

  - platform: template
    name: "RGBCT Light: RGB"
    id: rgbct_light_rgb_switch
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      - if:
          condition:
            switch.is_on: rgbct_light_power_switch
          then:
          - light.turn_on:
              id: rgbct_light
              color_mode: RGB
    turn_off_action:
      - if:
          condition:
            switch.is_on: rgbct_light_power_switch
          then:
          - light.turn_on:
              id: rgbct_light
              color_mode: COLOR_TEMPERATURE

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "ESPHome: Factory reset"

  - platform: restart
    name: "ESPHome: Restart"

  - platform: safe_mode
    name: "ESPHome: Safe Mode"