esphome:
  name: "presence"
  friendly_name: "Presence"
  name_add_mac_suffix: true
  on_boot:
    - priority: 600.0
      then:
        - lambda: |-
            // Default: Connecting
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(1000);
            id(wifi_led_pwm).turn_on();
        - script.execute: fast_reboot_factory_reset
        - switch.turn_off: ld2410_bluetooth
        - button.press: ld2410_query_params
  on_loop:
    then:
      - lambda: |-
          // Captive portal
          if(id(wifi_component).has_ap() && !id(wifi_component).has_sta()) {
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(200);
          } else {
            id(wifi_led_pwm).set_period(1000);
            // Connected
            if(id(wifi_component).is_connected())
              id(wifi_led_pwm).set_level(1);
            // Connecting
            else
              id(wifi_led_pwm).set_level(0.5);
          }

esp32:
  board: esp32-c3-devkitm-1

globals:
  - id: fast_reboot
    type: int
    restore_value: yes
    initial_value: '0'

  - id: factory_reset_reboot_counter
    type: int
    initial_value: '2'

logger:
  baud_rate: 0
  level: info

script:
  - id: fast_reboot_factory_reset
    then:
      - if:
          condition:
            lambda: return ( id(fast_reboot) >= id(factory_reset_reboot_counter) );
          then:
            - lambda: |-
                ESP_LOGI("Fast Boot Factory Reset", "Performing factotry reset");
                id(fast_reboot) = 0;
                fast_reboot->loop();
                global_preferences->sync();
            - button.press: factory_reset_button
      - lambda: |-
          if(id(fast_reboot) > 0)
            ESP_LOGI("Fast Boot Factory Reset", "Quick reboot %d/%d, do it %d more times to factory reset", id(fast_reboot), id(factory_reset_reboot_counter), id(factory_reset_reboot_counter) - id(fast_reboot));
          id(fast_reboot) += 1;
          fast_reboot->loop();
          global_preferences->sync();
      - delay: 10s
      - lambda: |-
          id(fast_reboot) = 0;
          fast_reboot->loop();
          global_preferences->sync();

wifi:
  id: wifi_component
  ap:
    ap_timeout: 0s
  reboot_timeout: 60s
  power_save_mode: none

captive_portal:
    
web_server:

api:
  reboot_timeout: 60s

ota:
  safe_mode: false

prometheus:

debug:
  update_interval: 5s

uart:
  baud_rate: 256000
  tx_pin: 2
  rx_pin: 1
  parity: NONE
  stop_bits: 1

i2c:
  sda: 7
  scl: 6
  scan: false

ld2410:
  id: ld2410_sensor

binary_sensor:
  - platform: status
    name: "Status"

  - platform: ld2410
    has_target:
      name: "Presence (UART)"
    has_moving_target:
      name: "Presence moving"
    has_still_target:
      name: "Presence still"
    out_pin_presence_status:
      name: "Presence GPIO indicates"

  - platform: gpio
    pin: 3
    id: presence_gpio
    name: "Presence (GPIO)"
    on_press:
      then:
        - output.turn_on: presence_led
    on_release:
      then:
        - output.turn_off: presence_led

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 15s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 15s

  - platform: debug
    free:
      name: "Debug: Heap Free"
    block:
      name: "Debug: Heap Largest Contiguous Free Block"
    loop_time:
      name: "Debug: Loop Time"

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 1s

  - platform: ld2410
    # Engineering Mode
    light:
      name: "Light"
    moving_distance:
      name: "Presence moving distance"
    still_distance:
      name: "Presence still distance"
    moving_energy:
      name: "Presence moving energy"
    still_energy:
      name: "Presence still energy"
    detection_distance:
      name: "Presence distance"
    g0:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 0 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 0 energy"
    g1:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 1 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 1 energy"
    g2:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 2 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 2 energy"
    g3:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 3 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 3 energy"
    g4:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 4 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 4 energy"
    g5:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 5 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 5 energy"
    g6:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 6 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 6 energy"
    g7:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 7 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 7 energy"
    g8:
      # Engineering Mode
      move_energy:
        name: "Presence moving gate 8 energy"
      # Engineering Mode
      still_energy:
        name: "Presence still gate 8 energy"

output:
  - platform: slow_pwm
    id: wifi_led_pwm
    period: 1s
    pin: 5

  - platform: gpio
    pin: 4
    id: presence_led

switch:
  - platform: ld2410
    engineering_mode:
      id: ld2410_engineering_mode
      name: "Engineering mode"
    bluetooth:
      id: ld2410_bluetooth
      name: "Bluetooth"

number:
  - platform: ld2410
    timeout:
      name: "Presence timeout"
      # unit_of_measurement: "s"
    light_threshold:
      name: "Light threshold"
    max_move_distance_gate:
      name: "Presence moving max distance gate"
    max_still_distance_gate:
      name: "Presence still max distance gate"
    g0:
      move_threshold:
        name: "Presence moving gate 0 threshold"
      still_threshold:
        name: "Presence still gate 0 threshold"
    g1:
      move_threshold:
        name: "Presence moving gate 1 threshold"
      still_threshold:
        name: "Presence still gate 1 threshold"
    g2:
      move_threshold:
        name: "Presence moving gate 2 threshold"
      still_threshold:
        name: "Presence still gate 2 threshold"
    g3:
      move_threshold:
        name: "Presence moving gate 3 threshold"
      still_threshold:
        name: "Presence still gate 3 threshold"
    g4:
      move_threshold:
        name: "Presence moving gate 4 threshold"
      still_threshold:
        name: "Presence still gate 4 threshold"
    g5:
      move_threshold:
        name: "Presence moving gate 5 threshold"
      still_threshold:
        name: "Presence still gate 5 threshold"
    g6:
      move_threshold:
        name: "Presence moving gate 6 threshold"
      still_threshold:
        name: "Presence still gate 6 threshold"
    g7:
      move_threshold:
        name: "Presence moving gate 7 threshold"
      still_threshold:
        name: "Presence still gate 7 threshold"
    g8:
      move_threshold:
        name: "Presence moving gate 8 threshold"
      still_threshold:
        name: "Presence still gate 8 threshold"

button:
  - platform: restart
    name: "Restart"

  - platform: safe_mode
    name: "Safe Mode"

  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset"

  - platform: ld2410
    factory_reset:
      name: "Factory reset"
    restart:
      id: ld2410_restart
      name: "Restart"
    query_params:
      id: ld2410_query_params
      name: "Query params"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Wifi Info: IP Address"
    ssid:
      name: "Wifi Info: SSID"
    bssid:
      name: "Wifi Info: BSSID"
    mac_address:
      name: "Wifi Info: MAC Address"
    dns_address:
      name: "Wifi Info: DNS Address"

  - platform: debug
    device:
      name: "Debug: Device Info"
    reset_reason:
      name: "Debug: Reset Reason"

  - platform: ld2410
    version:
      name: "Firmware version"
    mac_address:
      name: "Bluetooth MAC address"

select:
  - platform: ld2410
    distance_resolution:
      name: "Presence distance resolution"
    baud_rate:
      name: "Baud rate"
    light_function:
      name: "Light function"
    out_pin_level:
      name: "Presence GPIO pin level"

text:
  - platform: template
    name: "Bluetooth password"
    optimistic: true
    min_length: 6
    max_length: 6
    mode: text
    on_value:
      then:
        - bluetooth_password.set:
            id: ld2410_sensor
            password: !lambda "return x;"
